imports:
    - { resource: "state_machine/**/*.yml" }
    - { resource: 'resources/*.yml' }
    - { resource: 'services.xml' }
    - { resource: 'grids.yml' }
    - { resource: 'email/*.yml'}
    - { resource: "ui.yml"}
    - { resource: "fixtures.yml"}

sylius_ui:
    events:
        sylius.shop.custom.homepage:
            blocks:
                parts_search:
                    template: "@SyliusShop/Homepage/_search.html.twig"
                    priority: 20
                about_us:
                    template: "@SyliusShop/Homepage/_aboutUs.html.twig"
                    priority: 10
        sylius.shop.layout.footer:
            blocks:
                grid:
                    template: "@SyliusShop/Layout/Footer/_grid.html.twig"
                    priority: 20
                content:
                    template: "@SyliusShop/Layout/Footer/_content.html.twig"
                    priority: 10
                after_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 5
                    context:
                        event: sylius.shop.layout.after_footer
