imports:
    - { resource: "state_machine/**/*.yml" }
    - { resource: 'resources/*.yml' }
    - { resource: 'services.xml' }
    - { resource: 'grids.yml' }
    - { resource: 'email/*.yml'}
    - { resource: "ui.yml"}
    - { resource: "fixtures.yml"}

sylius_ui:
    events:
        sylius.shop.homepage:
            blocks:
                parts_search:
                    template: "@SyliusShop/Homepage/_search.html.twig"
                    priority: 70
                banner:
                    template: "@SyliusShop/Homepage/_banner.html.twig"
                    priority: 60
                latest_products:
                    template: "@SyliusShop/Homepage/_latestProducts.html.twig"
                    priority: 50
                latest_products_carousel:
                    template: "@SyliusShop/Homepage/_latestProductsCarousel.html.twig"
                    priority: 40
                newsletter:
                    template: "@SyliusShop/Homepage/_newsletter.html.twig"
                    priority: 30
                products_grid:
                    template: "@SyliusShop/Homepage/_productsGrid.html.twig"
                    priority: 20
                about_us:
                    template: "@SyliusShop/Homepage/_aboutUs.html.twig"
                    priority: 10
