vendor_profile:
    resource: "routing/vendor_profile.yml"
    prefix: /{_locale}/account
    requirements:
        _locale: ^[A-Za-z]{2,4}(_([A-Za-z]{4}|[0-9]{3}))?(_([A-Za-z]{2}|[0-9]{3}))?$
vendor_profile_update:
    resource: "routing/vendor_profile_update.yml"
    prefix: /{_locale}/account
    requirements:
        _locale: ^[A-Za-z]{2,4}(_([A-Za-z]{4}|[0-9]{3}))?(_([A-Za-z]{2}|[0-9]{3}))?$
vendor_register_form:
    resource: "routing/vendor_register_form.yml"
    prefix: /{_locale}/account
    requirements:
        _locale: ^[A-Za-z]{2,4}(_([A-Za-z]{4}|[0-9]{3}))?(_([A-Za-z]{2}|[0-9]{3}))?$

confirm_profile_update_link:
    resource: "routing/confirm_profile_update.yml"
    prefix: /{_locale}/account
    requirements:
        _locale: ^[A-Za-z]{2,4}(_([A-Za-z]{4}|[0-9]{3}))?(_([A-Za-z]{2}|[0-9]{3}))?$
vendor_registration:
    resource: "routing/vendor_register_form.yml"
    prefix: /{_locale}/account
    requirements:
        _locale: ^[A-Za-z]{2,4}(_([A-Za-z]{4}|[0-9]{3}))?(_([A-Za-z]{2}|[0-9]{3}))?$
app_admin:
    resource: 'routing/admin.yml'
    prefix: /admin
vendor_register:
    resource: "routing/vendor_register.yml"
    prefix: /{_locale}/account
    requirements:
        _locale: ^[A-Za-z]{2,4}(_([A-Za-z]{4}|[0-9]{3}))?(_([A-Za-z]{2}|[0-9]{3}))?$
app_vendor:
  resource: 'routing/vendor.yml'
  prefix: /{_locale}/account/vendor
app_shop:
    resource: 'routing/shop.yml'
    prefix: /{_locale}
    requirements:
        _locale: ^[A-Za-z]{2,4}(_([A-Za-z]{4}|[0-9]{3}))?(_([A-Za-z]{2}|[0-9]{3}))?$

sylius_shop_checkout_complete:
    resource: 'routing/shop/order.yml'
    prefix: /{_locale}

vendor_order_list:
    resource: 'routing/vendor/order_listing.yml'
    prefix: /{_locale}/account

conversation:
  resource: "routing/conversation.yml"

conversation_category:
    resource: "routing/admin/conversation_category.yml"

conversation_vendor:
  resource: "routing/vendor_conversation.yml"
  prefix: /{_locale}/account
  requirements:
      _locale: ^[A-Za-z]{2,4}(_([A-Za-z]{4}|[0-9]{3}))?(_([A-Za-z]{2}|[0-9]{3}))?$

open_marketplace_customer_index:
    resource: "routing/vendor/clients.yml"
    prefix: /{_locale}/account
    requirements:
        _locale: ^[A-Za-z]{2,4}(_([A-Za-z]{4}|[0-9]{3}))?(_([A-Za-z]{2}|[0-9]{3}))?$

open_marketplace_variants_index:
    resource: "routing/vendor/product_variants.yml"
    prefix: /{_locale}/account
    requirements:
        _locale: ^[A-Za-z]{2,4}(_([A-Za-z]{4}|[0-9]{3}))?(_([A-Za-z]{2}|[0-9]{3}))?$

draft_attributes:
    resource: 'routing/vendor/draft_attributes.yml'
    prefix: /{_locale}/account
    requirements:
        _locale: ^[A-Za-z]{2,4}(_([A-Za-z]{4}|[0-9]{3}))?(_([A-Za-z]{2}|[0-9]{3}))?$

vendor_shipping_methods:
  resource: "routing/vendor_shipping_methods.yml"
  prefix: /{_locale}/account
  requirements:
    _locale: ^[A-Za-z]{2,4}(_([A-Za-z]{4}|[0-9]{3}))?(_([A-Za-z]{2}|[0-9]{3}))?$

open_marketplace_vendor_product_reviews:
  resource: "routing/vendor/product_review.yml"
  prefix: /{_locale}/account/vendor
  requirements:
    _locale: ^[A-Za-z]{2,4}(_([A-Za-z]{4}|[0-9]{3}))?(_([A-Za-z]{2}|[0-9]{3}))?$
