sylius_resource:
    resources:
        open_marketplace.draft_attribute:
            classes:
                model: BitBag\OpenMarketplace\Entity\ProductListing\DraftAttribute
                interface: BitBag\OpenMarketplace\Entity\ProductListing\DraftAttributeInterface
                controller: Sylius\Bundle\ResourceBundle\Controller\ResourceController
                repository: BitBag\OpenMarketplace\Repository\DraftAttributeRepository
                form: BitBag\OpenMarketplace\Form\ProductListing\DraftAttributeType
            translation:
                classes:
                    model: BitBag\OpenMarketplace\Entity\ProductListing\DraftAttributeTranslation
        open_marketplace.draft_attribute_value:
            classes:
                model: BitBag\OpenMarketplace\Entity\ProductListing\DraftAttributeValue
