sylius_resource:
    resources:
        open_marketplace.product_listing:
            driver: doctrine/orm
            classes:
                model: BitBag\OpenMarketplace\Entity\ProductListing\ProductListing
                repository: BitBag\OpenMarketplace\Repository\ProductListing\ProductListingRepository

        open_marketplace.product_draft:
            driver: doctrine/orm
            classes:
                model: BitBag\OpenMarketplace\Entity\ProductListing\ProductDraft
                interface: BitBag\OpenMarketplace\Entity\ProductListing\ProductDraftInterface
                controller: Sylius\Bundle\ResourceBundle\Controller\ResourceController
                form: BitBag\OpenMarketplace\Form\ProductListing\ProductType

        open_marketplace.product_translation:
            driver: doctrine/orm
            classes:
                model: BitBag\OpenMarketplace\Entity\ProductListing\ProductTranslation
                interface: BitBag\OpenMarketplace\Entity\ProductListing\ProductTranslationInterface

        open_marketplace.product_listing_price:
            driver: doctrine/orm
            classes:
                model: BitBag\OpenMarketplace\Entity\ProductListing\ProductListingPrice
                interface: BitBag\OpenMarketplace\Entity\ProductListing\ProductListingPriceInterface

        open_marketplace.product_draft_image:
            driver: doctrine/orm
            classes:
                model: BitBag\OpenMarketplace\Entity\ProductListing\ProductDraftImage

        open_marketplace.product_draft_taxons:
            driver: doctrine/orm
            classes:
                model: BitBag\OpenMarketplace\Entity\ProductListing\ProductDraftTaxon
                interface: BitBag\OpenMarketplace\Entity\ProductListing\ProductDraftTaxonInterface
                repository: BitBag\OpenMarketplace\Repository\ProductListing\ProductDraftTaxonRepository
