sylius_resource:
    resources:
        open_marketplace.conversation:
            driver: doctrine/orm
            classes:
                model: BitBag\OpenMarketplace\Entity\Conversation\Conversation
                controller: Sylius\Bundle\ResourceBundle\Controller\ResourceController
                interface: BitBag\OpenMarketplace\Entity\Conversation\ConversationInterface
                repository: BitBag\OpenMarketplace\Repository\Conversation\ConversationRepository
                form: BitBag\OpenMarketplace\Form\Type\Conversation\ConversationType
