sylius_product:
  resources:
    product:
      classes:
        model: BitBag\OpenMarketplace\Entity\Product
        interface: BitBag\OpenMarketplace\Entity\ProductInterface
        repository: BitBag\OpenMarketplace\Repository\ProductRepository
